version: "3"

services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
